fix Vagrant 1.1 double quotes from ssh-config
Vagrant 1.1 introduces leading and trailing whitespaces for IdentityFile when queried with ```vagrant ssh-config```
this leads to

```
IOError: [Errno 2] No such file or directory: '"/Users/xyz/.vagrant.d/insecure_private_key"'
```

this patch removes the double quotes and keeps backward compatibility